//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPrep_BL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BP_ModelContainer : DbContext
    {
        public BP_ModelContainer()
            : base("name=BP_ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Prepper> Preppers { get; set; }
        public virtual DbSet<Kit> Kits { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemStatus> ItemStatus { get; set; }
        public virtual DbSet<SampleKit> SampleKits { get; set; }
        public virtual DbSet<SampleItem> SampleItems { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
    }
}
