//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPrep_BL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prepper
    {
        public Prepper()
        {
            this.Kits = new HashSet<Kit>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public System.DateTime ConfirmationRequestSent { get; set; }
        public string ConfirmationGuid { get; set; }
        public bool ShowTipKit { get; set; }
        public bool ShowTipKitItems { get; set; }
        public string UnsubscribeGuid { get; set; }
    
        public virtual ICollection<Kit> Kits { get; set; }
    }
}
