//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPrep_BL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public int SampleKitId { get; set; }
        public int DaysShelfLife { get; set; }
        public int DaysWarningOfReplacement { get; set; }
        public string Description { get; set; }
        public string AmazonWidget { get; set; }
    
        public virtual SampleKit SampleKit { get; set; }
    }
}
